[project]
name = "overengineering-my-singapore-holiday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "daniela-fernandes", email = "126296437+sdanifern@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.6",
    "requests>=2.34.2",
]

[project.scripts]
overengineering-my-singapore-holiday = "overengineering_my_singapore_holiday:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
